fix build followed the wiki
https://github.com/illumos/illumos-gate/commit/d1151f9bab097777251f26772ebcc50468637a12 breaks building

```
/usr/include/libcmdutils.h:41:2: error: #error "libcmdutils.h can only be used in a largefile compilation environment"
```